algorithm:
  class: OracleRM
  rm_label: true

checkpoint: null
seed: 0
name: default
debug: false
device: null
wandb:
  activate: false
  entity: null
  project: null

env: hopper-medium-replay-v2
env_kwargs:
env_wrapper:
env_wrapper_kwargs:

mode: human

optim:
  default:
    class: Adam
    lr: 0.0003

network:

rm_dataset:
  - class: IPLComparisonOfflineDataset
    env: <env>
    batch_size: 8
    segment_length: null
    mode: <mode>
rm_dataloader:
  num_workers: 2
  batch_size: null

rl_dataset:
  - class: D4RLOfflineDataset
    env: <env>
    batch_size: 256
    mode: transition
    reward_normalize: true
rl_dataloader:
  num_workers: 2
  batch_size: null

trainer:
  env_freq: null
  rm_label: true
  rm_steps: 200000
  rl_steps: 0
  log_freq: 500
  profile_freq: 500
  eval_freq: 5000

rm_eval:
  function: eval_reward_model
  eval_dataset_kwargs:
    class: IPLComparisonOfflineDataset
    env: <env>
    batch_size: 64
    mode: <mode>
    eval: true
  eval_offline_dataset_kwargs:
    class: D4RLOfflineDataset
    env: <env>
    batch_size: 256
    mode: trajectory
    reward_normalize: true
rl_eval:
  function: eval_offline
  num_ep: 10
  deterministic: true

schedulers:
  actor:
    class: CosineAnnealingLR
    T_max: 1000000

processor: null
